# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 73521f1b3e58b6a223f9639d9a5792ef84d17aaf1548971007c08036073d131da4c0f138e2dd9b8931149d97de2fb5d49b55f9d9d1389ddcf434f589912ecd06

test:
  secret_key_base: 1a029f58fef3427b9d25b13542bde79707c31fa1ddea3192095b6fc1bf3f9738e251b06065684f3ca84e92ac00e68cb4e02b75e64291e3625c1cb79effe4faf0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
